# Application details
spring.application.name=spring-learn

# Server configuration
# Spring Boot runs on 8080 by default. Set to 8083 for REST Country Web Service.
server.port=8083

# Logging levels
# Enable logging for framework and package
logging.level.org.springframework=INFO
logging.level.com.cognizant.springlearn=DEBUG
