# Application details
spring.application.name=spring-learn

# Server configuration
# Spring Boot runs on 8080 by default. Let's customize it to 8082 to demonstrate configuration flexibility.
server.port=8082

# Logging levels
# You can adjust logging levels (TRACE, DEBUG, INFO, WARN, ERROR) for specific packages.
logging.level.org.springframework=INFO
logging.level.com.cognizant.springlearn=DEBUG
